sudo: false
dist: trusty
language: node_js
env:
  - BROWSER=Chrome_travis_ci
  - BROWSER=firefox_linux
  - BROWSER=bs_safari_11
  - BROWSER=bs_ieEdge_windows
  - BROWSER=bs_ie11_windows
matrix:
  fast_finish: true
  allow_failures:
    - env: BROWSER=bs_ieEdge_windows
    - env: BROWSER=bs_ie11_windows
addons:
  chrome: stable
  firefox: latest
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set @folio:registry https://repository.folio.org/repository/npm-folioci/
install:
  - yarn
cache:
  yarn: true
script:
  - yarn lint --max-warnings=0
  - yarn test --karma.singleRun --karma.browsers=$BROWSER --coverage
