dist: trusty
language: node_js
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn test -- --single-run
before_deploy:
  - environment=production yarn build
deploy:
  provider: s3
  acl: public_read
  cache_control: max-age=30
  access_key_id: AKIAJS2B2FMG7GS4E5MA
  secret_access_key:
    secure: cWmzSE8PWpolL/yY92EvAemSxpnsO7B1Bqf+wC1AeeRjGvETwKbyzlUOvQGQuEEe27ja4mMyVcQLy5WHvgqpiarg492e7qqj4N7t7UlmFPULHbdWsGHLH/WxSIQ8erz/d08lP2tn18As4dOAGDXTlslfX946ZgB6c4mt5vVq02UiTFXTAcFGTs38/fAkY36CUKt5O28vcokS56wf5NqVR9cm49r7eOUQfQHoKvODr3pqGL63trgztQfUGm+Vpyp2j7Gd3ly5CK8+iN9pb4afQHfmNDlzUagGJWfR7Y8TwnTeGjYw8TNhnx+/MM1Uk/BTKKHJ5vpBZg5EMOk/reB4cs9Uin+KR0KiBG8DBOpPmJb+PtF9tmXScqf+jqcBZGIeI8cOknbyxk2J/ObhVFddErW2QuQcMS14ZzDzv5V/WVgEtqPAHGRAdSxQxfIz9TJjzeLjwa/Zz/gm9C29vkTmhZTaL+iRpTxN/f3cUhtmqpe0DOfzBZc0cCWK8Q/bA90ImKmOmeQwUUXOnxTsu23NOQIVSx57fxN9AxFYFoLYR6SPOKxrXiZswN8w6X0yf1SryOcSn6RPdnfBakFWVkx7sRAzW+3l4R4+bQ/klJ5y5wGrYWKtsxsb56klG4x8xIP6em7Bnlre8U10ck518y3YIzFv6YFIdj0w3MgNY06im1g=
  bucket: folio.frontside.io
  region: us-east-2
  skip_cleanup: true
  local_dir: platform/dist
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - https://fs-bitbot.herokuapp.com/travis
