sudo: false
dist: trusty
language: node_js
env:
  - BROWSER=Chrome_travis_ci
  - BROWSER=bs_safari_11
  - BROWSER=bs_firefox_mac
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set @folio:registry https://repository.folio.org/repository/npm-folioci/
install:
  - yarn
cache:
  yarn: true
script:
  - yarn lint --max-warnings=0
  - yarn test --karma.singleRun --karma.browsers=$BROWSER --coverage
