sudo: false
dist: trusty
language: node_js
env:
  - BROWSER=Chrome_travis_ci
  - BROWSER=bs_safari_11
matrix:
  allow_failures:
    - env: BROWSER=bs_safari_11
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
cache:
  yarn: true
script:
  - yarn lint
  - yarn test --single-run --browsers=$BROWSER
before_deploy:
  - NODE_ENV=production yarn build
deploy:
  provider: s3
  acl: public_read
  cache_control: max-age=30
  access_key_id: AKIAJPCMT5BOKFDIIAQQ
  secret_access_key:
    secure: wvapi16jVwXoSmYQstKLYbLXtNcn+pYb2YgN5lHds8hW5Lg0OW2L0kGO2PIbnb00hfFln3AKEAvZrRshHH8sZKmLu1IZjnc/TZWNHUW3E/ClCQkurmk1rW+E5bOCSUiER+DlMpffzwiZpP9u/syuxTLXG/tqTP3iUo0ExY4TjMe6l8dTr8+LQbnFpYwjdikn47lUZMVdN8+BgbBkEjBNYpwR9bng44hpRN+UD87pYJias+03fppqLxD3iyK/R75ivSPuqjG9QhZcXZqZvAROUd5kGvspKRIdeqlCqu9+gfa1JrQWQ2tjrUwi1xgHUG5aUgvx58s3cq8/94D1PGlBbNMrucA2CtvHsm5C8efYjxc1jEBeos5WwPf4xdv23st/JyX14JfoXSuQ7j9WM49c+MXcxE8tSw9h+jyd1wpIwSZbySFXdlRE6GnekLVJLNhMThW5ESchPMRS6OBi9iZoA/tHzaskiR47uRpO5f3yJ5m8PZzeJ1wEVOsJgvBskxC3AqEms/U6WDtXr48PIE06T9jwESV1f5Mmf3ziGGA3yeRJ41TtAmCvcnyoA9xre9kZzzwg0iB61sJKFp47nkU+WtTCjm6Pf6VDrnetxh6JLIUcGhUq5Ku3SXDc1G7f6mWfVPdxOKmF9XITU6gTVXONLDtR6pXEx6Taf3jUZuXbDZM=
  bucket: folio.frontside.io
  region: us-east-2
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - https://fs-bitbot.herokuapp.com/travis
