sudo: false
dist: trusty
language: node_js
env:
  - BROWSER=Chrome_travis_ci
  - BROWSER=bs_safari_11
  - BROWSER=bs_firefox_mac
  - BROWSER=bs_ieEdge_windows
  - BROWSER=bs_ie11_windows
matrix:
  fast_finish: true
  allow_failures:
    - env: BROWSER=bs_firefox_mac
    - env: BROWSER=bs_ieEdge_windows
    - env: BROWSER=bs_ie11_windows
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm config set @folio:registry https://repository.folio.org/repository/npm-folioci/
install:
  - yarn
cache:
  yarn: true
script:
  - yarn lint --max-warnings=0
  - yarn test --karma.singleRun --karma.browsers=$BROWSER --coverage
