version: 2.0

jobs:
  checkout-and-install:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - persist_to_workspace:
          root: ~/
          paths: project
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules

  eslint:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint JS
          command: yarn eslint --max-warnings=0

  stylelint:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint CSS
          command: yarn stylelint

  build:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build bundle
          command: NODE_ENV=production yarn build

  test-chrome:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test --karma.singleRun --karma.browsers=Chrome --karma.reporters mocha junit --coverage
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          name: Store junit test report
          path: ./artifacts/junit
      - store_artifacts:
          name: Store code coverage report
          path: ./artifacts/coverage/lcov.txt

  test-safari:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test --karma.singleRun --karma.browsers=bs_safari_11 --karma.reporters mocha junit BrowserStack
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          name: Store junit test report
          path: ./artifacts/junit

  test-firefox:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install the latest Firefox ESR
          command: |
            sudo apt-get remove firefox-mozilla-build &&
            sudo apt install firefox-esr &&
            firefox --version
      - run:
          name: Run tests
          command: yarn test --karma.singleRun --karma.browsers=Firefox --karma.reporters mocha junit
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          name: Store junit test report
          path: ./artifacts/junit

  test-edge:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test --karma.singleRun --karma.browsers=bs_ieEdge_windows --karma.reporters mocha junit BrowserStack || true
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          name: Store junit test report
          path: ./artifacts/junit

  test-ie:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test --karma.singleRun --karma.browsers=bs_ie11_windows --karma.reporters mocha junit BrowserStack || true
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          name: Store junit test report
          path: ./artifacts/junit

workflows:
  version: 2
  push:
    jobs:
      - checkout-and-install
      - eslint:
          requires:
            - checkout-and-install
      - stylelint:
          requires:
            - checkout-and-install
      - build:
          requires:
            - checkout-and-install
      - test-chrome:
          requires:
            - checkout-and-install
